/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MasterRouteRouteImport } from './routes/master/route'
import { Route as VendedorRouteImport } from './routes/vendedor'
import { Route as MasterIndexRouteImport } from './routes/master/index'
import { Route as MasterCatalogoIndexRouteImport } from './routes/master/catalogo/index'
import { Route as MasterCatalogoProductIdRouteImport } from './routes/master/catalogo/$productId'
import { Route as MasterCatalogoNovoRouteImport } from './routes/master/catalogo/novo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterRouteRoute = MasterRouteRouteImport.update({
  id: '/master',
  path: '/master',
  getParentRoute: () => rootRouteImport,
} as any)
const VendedorRoute = VendedorRouteImport.update({
  id: '/vendedor',
  path: '/vendedor',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterIndexRoute = MasterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MasterRouteRoute,
} as any)
const MasterCatalogoIndexRoute = MasterCatalogoIndexRouteImport.update({
  id: '/catalogo/',
  path: '/catalogo/',
  getParentRoute: () => MasterRouteRoute,
} as any)
const MasterCatalogoProductIdRoute = MasterCatalogoProductIdRouteImport.update({
  id: '/catalogo/$productId',
  path: '/catalogo/$productId',
  getParentRoute: () => MasterRouteRoute,
} as any)
const MasterCatalogoNovoRoute = MasterCatalogoNovoRouteImport.update({
  id: '/catalogo/novo',
  path: '/catalogo/novo',
  getParentRoute: () => MasterRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/master': typeof MasterRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/vendedor': typeof VendedorRoute
  '/master/': typeof MasterIndexRoute
  '/master/catalogo/$productId': typeof MasterCatalogoProductIdRoute
  '/master/catalogo/novo': typeof MasterCatalogoNovoRoute
  '/master/catalogo/': typeof MasterCatalogoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/vendedor': typeof VendedorRoute
  '/master': typeof MasterIndexRoute
  '/master/catalogo/$productId': typeof MasterCatalogoProductIdRoute
  '/master/catalogo/novo': typeof MasterCatalogoNovoRoute
  '/master/catalogo': typeof MasterCatalogoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/master': typeof MasterRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/vendedor': typeof VendedorRoute
  '/master/': typeof MasterIndexRoute
  '/master/catalogo/$productId': typeof MasterCatalogoProductIdRoute
  '/master/catalogo/novo': typeof MasterCatalogoNovoRoute
  '/master/catalogo/': typeof MasterCatalogoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/master'
    | '/login'
    | '/vendedor'
    | '/master/'
    | '/master/catalogo/$productId'
    | '/master/catalogo/novo'
    | '/master/catalogo/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/vendedor'
    | '/master'
    | '/master/catalogo/$productId'
    | '/master/catalogo/novo'
    | '/master/catalogo'
  id:
    | '__root__'
    | '/'
    | '/master'
    | '/login'
    | '/vendedor'
    | '/master/'
    | '/master/catalogo/$productId'
    | '/master/catalogo/novo'
    | '/master/catalogo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MasterRouteRoute: typeof MasterRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  VendedorRoute: typeof VendedorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master': {
      id: '/master'
      path: '/master'
      fullPath: '/master'
      preLoaderRoute: typeof MasterRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendedor': {
      id: '/vendedor'
      path: '/vendedor'
      fullPath: '/vendedor'
      preLoaderRoute: typeof VendedorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/': {
      id: '/master/'
      path: '/'
      fullPath: '/master/'
      preLoaderRoute: typeof MasterIndexRouteImport
      parentRoute: typeof MasterRouteRoute
    }
    '/master/catalogo/': {
      id: '/master/catalogo/'
      path: '/catalogo'
      fullPath: '/master/catalogo/'
      preLoaderRoute: typeof MasterCatalogoIndexRouteImport
      parentRoute: typeof MasterRouteRoute
    }
    '/master/catalogo/$productId': {
      id: '/master/catalogo/$productId'
      path: '/catalogo/$productId'
      fullPath: '/master/catalogo/$productId'
      preLoaderRoute: typeof MasterCatalogoProductIdRouteImport
      parentRoute: typeof MasterRouteRoute
    }
    '/master/catalogo/novo': {
      id: '/master/catalogo/novo'
      path: '/catalogo/novo'
      fullPath: '/master/catalogo/novo'
      preLoaderRoute: typeof MasterCatalogoNovoRouteImport
      parentRoute: typeof MasterRouteRoute
    }
  }
}

interface MasterRouteRouteChildren {
  MasterIndexRoute: typeof MasterIndexRoute
  MasterCatalogoProductIdRoute: typeof MasterCatalogoProductIdRoute
  MasterCatalogoNovoRoute: typeof MasterCatalogoNovoRoute
  MasterCatalogoIndexRoute: typeof MasterCatalogoIndexRoute
}

const MasterRouteRouteChildren: MasterRouteRouteChildren = {
  MasterIndexRoute: MasterIndexRoute,
  MasterCatalogoProductIdRoute: MasterCatalogoProductIdRoute,
  MasterCatalogoNovoRoute: MasterCatalogoNovoRoute,
  MasterCatalogoIndexRoute: MasterCatalogoIndexRoute,
}

const MasterRouteRouteWithChildren = MasterRouteRoute._addFileChildren(
  MasterRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MasterRouteRoute: MasterRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  VendedorRoute: VendedorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
