/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MasterRouteRouteImport } from './routes/master/route'
import { Route as VendedorRouteRouteImport } from './routes/vendedor/route'
import { Route as MasterIndexRouteImport } from './routes/master/index'
import { Route as MasterDespesasRouteImport } from './routes/master/despesas'
import { Route as MasterDreRouteImport } from './routes/master/dre'
import { Route as MasterEncomendasRouteImport } from './routes/master/encomendas'
import { Route as MasterFluxoCaixaRouteImport } from './routes/master/fluxo-caixa'
import { Route as MasterRelatoriosRouteImport } from './routes/master/relatorios'
import { Route as MasterUsuariosRouteImport } from './routes/master/usuarios'
import { Route as VendedorIndexRouteImport } from './routes/vendedor/index'
import { Route as VendedorEncomendasRouteImport } from './routes/vendedor/encomendas'
import { Route as MasterCatalogoIndexRouteImport } from './routes/master/catalogo/index'
import { Route as MasterCatalogoProductIdRouteImport } from './routes/master/catalogo/$productId'
import { Route as MasterCatalogoNovoRouteImport } from './routes/master/catalogo/novo'
import { Route as MasterComprasCorrigirRouteImport } from './routes/master/compras/corrigir'
import { Route as MasterComprasNovaRouteImport } from './routes/master/compras/nova'
import { Route as MasterVendasDevolucaoRouteImport } from './routes/master/vendas/devolucao'
import { Route as MasterVendasHistoricoRouteImport } from './routes/master/vendas/historico'
import { Route as VendedorVendasNovaRouteImport } from './routes/vendedor/vendas/nova'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterRouteRoute = MasterRouteRouteImport.update({
  id: '/master',
  path: '/master',
  getParentRoute: () => rootRouteImport,
} as any)
const VendedorRouteRoute = VendedorRouteRouteImport.update({
  id: '/vendedor',
  path: '/vendedor',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterIndexRoute = MasterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MasterRouteRoute,
} as any)
const MasterDespesasRoute = MasterDespesasRouteImport.update({
  id: '/despesas',
  path: '/despesas',
  getParentRoute: () => MasterRouteRoute,
} as any)
const MasterDreRoute = MasterDreRouteImport.update({
  id: '/dre',
  path: '/dre',
  getParentRoute: () => MasterRouteRoute,
} as any)
const MasterEncomendasRoute = MasterEncomendasRouteImport.update({
  id: '/encomendas',
  path: '/encomendas',
  getParentRoute: () => MasterRouteRoute,
} as any)
const MasterFluxoCaixaRoute = MasterFluxoCaixaRouteImport.update({
  id: '/fluxo-caixa',
  path: '/fluxo-caixa',
  getParentRoute: () => MasterRouteRoute,
} as any)
const MasterRelatoriosRoute = MasterRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => MasterRouteRoute,
} as any)
const MasterUsuariosRoute = MasterUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => MasterRouteRoute,
} as any)
const VendedorIndexRoute = VendedorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VendedorRouteRoute,
} as any)
const VendedorEncomendasRoute = VendedorEncomendasRouteImport.update({
  id: '/encomendas',
  path: '/encomendas',
  getParentRoute: () => VendedorRouteRoute,
} as any)
const MasterCatalogoIndexRoute = MasterCatalogoIndexRouteImport.update({
  id: '/catalogo/',
  path: '/catalogo/',
  getParentRoute: () => MasterRouteRoute,
} as any)
const MasterCatalogoProductIdRoute = MasterCatalogoProductIdRouteImport.update({
  id: '/catalogo/$productId',
  path: '/catalogo/$productId',
  getParentRoute: () => MasterRouteRoute,
} as any)
const MasterCatalogoNovoRoute = MasterCatalogoNovoRouteImport.update({
  id: '/catalogo/novo',
  path: '/catalogo/novo',
  getParentRoute: () => MasterRouteRoute,
} as any)
const MasterComprasCorrigirRoute = MasterComprasCorrigirRouteImport.update({
  id: '/compras/corrigir',
  path: '/compras/corrigir',
  getParentRoute: () => MasterRouteRoute,
} as any)
const MasterComprasNovaRoute = MasterComprasNovaRouteImport.update({
  id: '/compras/nova',
  path: '/compras/nova',
  getParentRoute: () => MasterRouteRoute,
} as any)
const MasterVendasDevolucaoRoute = MasterVendasDevolucaoRouteImport.update({
  id: '/vendas/devolucao',
  path: '/vendas/devolucao',
  getParentRoute: () => MasterRouteRoute,
} as any)
const MasterVendasHistoricoRoute = MasterVendasHistoricoRouteImport.update({
  id: '/vendas/historico',
  path: '/vendas/historico',
  getParentRoute: () => MasterRouteRoute,
} as any)
const VendedorVendasNovaRoute = VendedorVendasNovaRouteImport.update({
  id: '/vendas/nova',
  path: '/vendas/nova',
  getParentRoute: () => VendedorRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/master': typeof MasterRouteRouteWithChildren
  '/vendedor': typeof VendedorRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/master/despesas': typeof MasterDespesasRoute
  '/master/dre': typeof MasterDreRoute
  '/master/encomendas': typeof MasterEncomendasRoute
  '/master/fluxo-caixa': typeof MasterFluxoCaixaRoute
  '/master/relatorios': typeof MasterRelatoriosRoute
  '/master/usuarios': typeof MasterUsuariosRoute
  '/vendedor/encomendas': typeof VendedorEncomendasRoute
  '/master/': typeof MasterIndexRoute
  '/vendedor/': typeof VendedorIndexRoute
  '/master/catalogo/$productId': typeof MasterCatalogoProductIdRoute
  '/master/catalogo/novo': typeof MasterCatalogoNovoRoute
  '/master/compras/corrigir': typeof MasterComprasCorrigirRoute
  '/master/compras/nova': typeof MasterComprasNovaRoute
  '/master/vendas/devolucao': typeof MasterVendasDevolucaoRoute
  '/master/vendas/historico': typeof MasterVendasHistoricoRoute
  '/vendedor/vendas/nova': typeof VendedorVendasNovaRoute
  '/master/catalogo/': typeof MasterCatalogoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/master/despesas': typeof MasterDespesasRoute
  '/master/dre': typeof MasterDreRoute
  '/master/encomendas': typeof MasterEncomendasRoute
  '/master/fluxo-caixa': typeof MasterFluxoCaixaRoute
  '/master/relatorios': typeof MasterRelatoriosRoute
  '/master/usuarios': typeof MasterUsuariosRoute
  '/vendedor/encomendas': typeof VendedorEncomendasRoute
  '/master': typeof MasterIndexRoute
  '/vendedor': typeof VendedorIndexRoute
  '/master/catalogo/$productId': typeof MasterCatalogoProductIdRoute
  '/master/catalogo/novo': typeof MasterCatalogoNovoRoute
  '/master/compras/corrigir': typeof MasterComprasCorrigirRoute
  '/master/compras/nova': typeof MasterComprasNovaRoute
  '/master/vendas/devolucao': typeof MasterVendasDevolucaoRoute
  '/master/vendas/historico': typeof MasterVendasHistoricoRoute
  '/vendedor/vendas/nova': typeof VendedorVendasNovaRoute
  '/master/catalogo': typeof MasterCatalogoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/master': typeof MasterRouteRouteWithChildren
  '/vendedor': typeof VendedorRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/master/despesas': typeof MasterDespesasRoute
  '/master/dre': typeof MasterDreRoute
  '/master/encomendas': typeof MasterEncomendasRoute
  '/master/fluxo-caixa': typeof MasterFluxoCaixaRoute
  '/master/relatorios': typeof MasterRelatoriosRoute
  '/master/usuarios': typeof MasterUsuariosRoute
  '/vendedor/encomendas': typeof VendedorEncomendasRoute
  '/master/': typeof MasterIndexRoute
  '/vendedor/': typeof VendedorIndexRoute
  '/master/catalogo/$productId': typeof MasterCatalogoProductIdRoute
  '/master/catalogo/novo': typeof MasterCatalogoNovoRoute
  '/master/compras/corrigir': typeof MasterComprasCorrigirRoute
  '/master/compras/nova': typeof MasterComprasNovaRoute
  '/master/vendas/devolucao': typeof MasterVendasDevolucaoRoute
  '/master/vendas/historico': typeof MasterVendasHistoricoRoute
  '/vendedor/vendas/nova': typeof VendedorVendasNovaRoute
  '/master/catalogo/': typeof MasterCatalogoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/master'
    | '/vendedor'
    | '/login'
    | '/master/despesas'
    | '/master/dre'
    | '/master/encomendas'
    | '/master/fluxo-caixa'
    | '/master/relatorios'
    | '/master/usuarios'
    | '/vendedor/encomendas'
    | '/master/'
    | '/vendedor/'
    | '/master/catalogo/$productId'
    | '/master/catalogo/novo'
    | '/master/compras/corrigir'
    | '/master/compras/nova'
    | '/master/vendas/devolucao'
    | '/master/vendas/historico'
    | '/vendedor/vendas/nova'
    | '/master/catalogo/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/master/despesas'
    | '/master/dre'
    | '/master/encomendas'
    | '/master/fluxo-caixa'
    | '/master/relatorios'
    | '/master/usuarios'
    | '/vendedor/encomendas'
    | '/master'
    | '/vendedor'
    | '/master/catalogo/$productId'
    | '/master/catalogo/novo'
    | '/master/compras/corrigir'
    | '/master/compras/nova'
    | '/master/vendas/devolucao'
    | '/master/vendas/historico'
    | '/vendedor/vendas/nova'
    | '/master/catalogo'
  id:
    | '__root__'
    | '/'
    | '/master'
    | '/vendedor'
    | '/login'
    | '/master/despesas'
    | '/master/dre'
    | '/master/encomendas'
    | '/master/fluxo-caixa'
    | '/master/relatorios'
    | '/master/usuarios'
    | '/vendedor/encomendas'
    | '/master/'
    | '/vendedor/'
    | '/master/catalogo/$productId'
    | '/master/catalogo/novo'
    | '/master/compras/corrigir'
    | '/master/compras/nova'
    | '/master/vendas/devolucao'
    | '/master/vendas/historico'
    | '/vendedor/vendas/nova'
    | '/master/catalogo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MasterRouteRoute: typeof MasterRouteRouteWithChildren
  VendedorRouteRoute: typeof VendedorRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master': {
      id: '/master'
      path: '/master'
      fullPath: '/master'
      preLoaderRoute: typeof MasterRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendedor': {
      id: '/vendedor'
      path: '/vendedor'
      fullPath: '/vendedor'
      preLoaderRoute: typeof VendedorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/': {
      id: '/master/'
      path: '/'
      fullPath: '/master/'
      preLoaderRoute: typeof MasterIndexRouteImport
      parentRoute: typeof MasterRouteRoute
    }
    '/master/despesas': {
      id: '/master/despesas'
      path: '/despesas'
      fullPath: '/master/despesas'
      preLoaderRoute: typeof MasterDespesasRouteImport
      parentRoute: typeof MasterRouteRoute
    }
    '/master/dre': {
      id: '/master/dre'
      path: '/dre'
      fullPath: '/master/dre'
      preLoaderRoute: typeof MasterDreRouteImport
      parentRoute: typeof MasterRouteRoute
    }
    '/master/encomendas': {
      id: '/master/encomendas'
      path: '/encomendas'
      fullPath: '/master/encomendas'
      preLoaderRoute: typeof MasterEncomendasRouteImport
      parentRoute: typeof MasterRouteRoute
    }
    '/master/fluxo-caixa': {
      id: '/master/fluxo-caixa'
      path: '/fluxo-caixa'
      fullPath: '/master/fluxo-caixa'
      preLoaderRoute: typeof MasterFluxoCaixaRouteImport
      parentRoute: typeof MasterRouteRoute
    }
    '/master/relatorios': {
      id: '/master/relatorios'
      path: '/relatorios'
      fullPath: '/master/relatorios'
      preLoaderRoute: typeof MasterRelatoriosRouteImport
      parentRoute: typeof MasterRouteRoute
    }
    '/master/usuarios': {
      id: '/master/usuarios'
      path: '/usuarios'
      fullPath: '/master/usuarios'
      preLoaderRoute: typeof MasterUsuariosRouteImport
      parentRoute: typeof MasterRouteRoute
    }
    '/vendedor/': {
      id: '/vendedor/'
      path: '/'
      fullPath: '/vendedor/'
      preLoaderRoute: typeof VendedorIndexRouteImport
      parentRoute: typeof VendedorRouteRoute
    }
    '/vendedor/encomendas': {
      id: '/vendedor/encomendas'
      path: '/encomendas'
      fullPath: '/vendedor/encomendas'
      preLoaderRoute: typeof VendedorEncomendasRouteImport
      parentRoute: typeof VendedorRouteRoute
    }
    '/master/catalogo/': {
      id: '/master/catalogo/'
      path: '/catalogo'
      fullPath: '/master/catalogo/'
      preLoaderRoute: typeof MasterCatalogoIndexRouteImport
      parentRoute: typeof MasterRouteRoute
    }
    '/master/catalogo/$productId': {
      id: '/master/catalogo/$productId'
      path: '/catalogo/$productId'
      fullPath: '/master/catalogo/$productId'
      preLoaderRoute: typeof MasterCatalogoProductIdRouteImport
      parentRoute: typeof MasterRouteRoute
    }
    '/master/catalogo/novo': {
      id: '/master/catalogo/novo'
      path: '/catalogo/novo'
      fullPath: '/master/catalogo/novo'
      preLoaderRoute: typeof MasterCatalogoNovoRouteImport
      parentRoute: typeof MasterRouteRoute
    }
    '/master/compras/corrigir': {
      id: '/master/compras/corrigir'
      path: '/compras/corrigir'
      fullPath: '/master/compras/corrigir'
      preLoaderRoute: typeof MasterComprasCorrigirRouteImport
      parentRoute: typeof MasterRouteRoute
    }
    '/master/compras/nova': {
      id: '/master/compras/nova'
      path: '/compras/nova'
      fullPath: '/master/compras/nova'
      preLoaderRoute: typeof MasterComprasNovaRouteImport
      parentRoute: typeof MasterRouteRoute
    }
    '/master/vendas/devolucao': {
      id: '/master/vendas/devolucao'
      path: '/vendas/devolucao'
      fullPath: '/master/vendas/devolucao'
      preLoaderRoute: typeof MasterVendasDevolucaoRouteImport
      parentRoute: typeof MasterRouteRoute
    }
    '/master/vendas/historico': {
      id: '/master/vendas/historico'
      path: '/vendas/historico'
      fullPath: '/master/vendas/historico'
      preLoaderRoute: typeof MasterVendasHistoricoRouteImport
      parentRoute: typeof MasterRouteRoute
    }
    '/vendedor/vendas/nova': {
      id: '/vendedor/vendas/nova'
      path: '/vendas/nova'
      fullPath: '/vendedor/vendas/nova'
      preLoaderRoute: typeof VendedorVendasNovaRouteImport
      parentRoute: typeof VendedorRouteRoute
    }
  }
}

interface MasterRouteRouteChildren {
  MasterDespesasRoute: typeof MasterDespesasRoute
  MasterDreRoute: typeof MasterDreRoute
  MasterEncomendasRoute: typeof MasterEncomendasRoute
  MasterFluxoCaixaRoute: typeof MasterFluxoCaixaRoute
  MasterRelatoriosRoute: typeof MasterRelatoriosRoute
  MasterUsuariosRoute: typeof MasterUsuariosRoute
  MasterIndexRoute: typeof MasterIndexRoute
  MasterCatalogoProductIdRoute: typeof MasterCatalogoProductIdRoute
  MasterCatalogoNovoRoute: typeof MasterCatalogoNovoRoute
  MasterComprasCorrigirRoute: typeof MasterComprasCorrigirRoute
  MasterComprasNovaRoute: typeof MasterComprasNovaRoute
  MasterVendasDevolucaoRoute: typeof MasterVendasDevolucaoRoute
  MasterVendasHistoricoRoute: typeof MasterVendasHistoricoRoute
  MasterCatalogoIndexRoute: typeof MasterCatalogoIndexRoute
}

const MasterRouteRouteChildren: MasterRouteRouteChildren = {
  MasterDespesasRoute: MasterDespesasRoute,
  MasterDreRoute: MasterDreRoute,
  MasterEncomendasRoute: MasterEncomendasRoute,
  MasterFluxoCaixaRoute: MasterFluxoCaixaRoute,
  MasterRelatoriosRoute: MasterRelatoriosRoute,
  MasterUsuariosRoute: MasterUsuariosRoute,
  MasterIndexRoute: MasterIndexRoute,
  MasterCatalogoProductIdRoute: MasterCatalogoProductIdRoute,
  MasterCatalogoNovoRoute: MasterCatalogoNovoRoute,
  MasterComprasCorrigirRoute: MasterComprasCorrigirRoute,
  MasterComprasNovaRoute: MasterComprasNovaRoute,
  MasterVendasDevolucaoRoute: MasterVendasDevolucaoRoute,
  MasterVendasHistoricoRoute: MasterVendasHistoricoRoute,
  MasterCatalogoIndexRoute: MasterCatalogoIndexRoute,
}

const MasterRouteRouteWithChildren = MasterRouteRoute._addFileChildren(
  MasterRouteRouteChildren,
)

interface VendedorRouteRouteChildren {
  VendedorEncomendasRoute: typeof VendedorEncomendasRoute
  VendedorIndexRoute: typeof VendedorIndexRoute
  VendedorVendasNovaRoute: typeof VendedorVendasNovaRoute
}

const VendedorRouteRouteChildren: VendedorRouteRouteChildren = {
  VendedorEncomendasRoute: VendedorEncomendasRoute,
  VendedorIndexRoute: VendedorIndexRoute,
  VendedorVendasNovaRoute: VendedorVendasNovaRoute,
}

const VendedorRouteRouteWithChildren = VendedorRouteRoute._addFileChildren(
  VendedorRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MasterRouteRoute: MasterRouteRouteWithChildren,
  VendedorRouteRoute: VendedorRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
